// compress-images.cjs
// Run with: node scripts/compress-images.cjs
// Converts all PNG/JPG in src/assets to WebP (quality 80) and generates LQIP placeholders

const sharp = require('sharp');
const fs = require('fs');
const path = require('path');

const ASSETS_DIR = path.join(__dirname, '../src/assets');
const WEBP_DIR = path.join(__dirname, '../src/assets/webp');
const LQIP_FILE = path.join(__dirname, '../src/assets/lqip.ts');

// Ensure output dir exists
if (!fs.existsSync(WEBP_DIR)) {
    fs.mkdirSync(WEBP_DIR, { recursive: true });
}

const supported = ['.jpg', '.jpeg', '.png'];

async function processImage(filePath) {
    const ext = path.extname(filePath).toLowerCase();
    if (!supported.includes(ext)) return null;

    const baseName = path.basename(filePath, ext);
    const outPath = path.join(WEBP_DIR, baseName + '.webp');

    const imgSharp = sharp(filePath);
    const meta = await imgSharp.metadata();

    // Convert to WebP at quality 80
    await imgSharp
        .webp({ quality: 80, effort: 4 })
        .toFile(outPath);

    // Generate LQIP: tiny 20px wide thumbnail as base64 WebP
    const lqipBuffer = await sharp(filePath)
        .resize(20, null, { withoutEnlargement: true })
        .webp({ quality: 20 })
        .toBuffer();

    const lqipBase64 = `data:image/webp;base64,${lqipBuffer.toString('base64')}`;

    const origSizeMB = (fs.statSync(filePath).size / 1024 / 1024).toFixed(2);
    const newSizeMB = (fs.statSync(outPath).size / 1024 / 1024).toFixed(2);
    console.log(`✓ ${baseName}${ext} → ${baseName}.webp  [${origSizeMB}MB → ${newSizeMB}MB]`);

    return { baseName, lqipBase64 };
}

async function main() {
    const files = fs.readdirSync(ASSETS_DIR).filter(f => {
        const ext = path.extname(f).toLowerCase();
        return supported.includes(ext);
    });

    console.log(`\nProcessing ${files.length} images...\n`);

    const results = [];
    for (const file of files) {
        const result = await processImage(path.join(ASSETS_DIR, file));
        if (result) results.push(result);
    }

    // Write lqip.ts file
    const lines = [
        '// AUTO-GENERATED by compress-images.cjs — do not edit manually',
        '// LQIP (Low Quality Image Placeholder) base64 strings for blur-up progressive loading',
        '',
    ];

    for (const { baseName, lqipBase64 } of results) {
        // Convert baseName to valid JS identifier
        const varName = baseName
            .replace(/[^a-zA-Z0-9_]/g, '_')
            .replace(/^(\d)/, '_$1');
        lines.push(`export const lqip_${varName} = "${lqipBase64}";`);
    }

    fs.writeFileSync(LQIP_FILE, lines.join('\n') + '\n');
    console.log(`\n✓ LQIP file written: src/assets/lqip.ts`);
    console.log(`✓ Done! ${results.length} images compressed to src/assets/webp/`);
}

main().catch(e => {
    console.error('Error:', e);
    process.exit(1);
});
